### ISSUE TITLE
[Feature Request] Sharable gurgle to play together

### ISSUE THREAD

**Issue by codingotaku** [billthefarmer/gurgle#11]
It would be amazing if one can share a [random seed](https://en.m.wikipedia.org/wiki/Random_seed) with others so that friends can compete each other to guess the same words.

**Comment by billthefarmer** [comment]
I will investigate that &ndash; possibly a QR code.

**Comment by billthefarmer** [comment]
Something like this...

![Screenshot_20220202-200826 1](https://user-images.githubusercontent.com/3448386/152229574-b7e6d014-b1f6-4eaf-b1f2-41d1ea32c270.png)

**Comment by codingotaku** [comment]
Brilliant!

**Comment by billthefarmer** [comment]
That will take a while, it's one thing to display a code, it's another to decode one.

**Comment by jmichael2497** [comment]
thanks to the pandemic, most folks should already have qrcode reading app, but why limit yourself?

maybe go with simple export/import menu to share as a string in whatever way people want like maybe qrcode, social media, messaging app, carrier pigeon.

this could also allow for the fun of for example a classic game that allowed typing in whatever for a seed to setup a map, so people could have their own name or phone number level.

**Comment by codingotaku** [comment]
> maybe go with simple export/import menu to share as a string in whatever way people want like maybe qrcode, social media, messaging app, carrier pigeon.

I think the “SHARE” option in the preview bill posted already share the string along with the QR image. `MTY0MzgzMjQ1MjcxNw==` evaluates to `1643832452717` it is the seed value.

**Comment by billthefarmer** [comment]
OK, I have released a new version with this enhancement. Receiving a code will not start the new sequence if a game is in progress. Tapping refresh will start the sequence. The QR code decoder will decode an image sent from the app, but is not so good using the camera.

**Comment by petazonk** [comment]
What about if players start a game in the same minute (or even same 10 seconds) then they get the same word? 

Or allow people to upload their own numbered word list and then you can pick a number that corresponds to the word. Other players could use the same word list and you could agree on a number that you want to play.

**Comment by billthefarmer** [comment]
Only if they start it within one second. The random seed is seconds since 1/1/1970 00:00 which is due to roll over in 32 bit numbers in 2038. As everything will probably be 64 bit by then it won't be an issue for another 2^63 - 2^31 seconds.
