### ISSUE TITLE
Keyboard doesn't fit in the screen when font size is larger than default

### ISSUE THREAD

**Issue by LuccoJ** [billthefarmer/gurgle#12]
I have a phone with fonts set to be larger than the default, due to the person using it having eyesight issues.

Gurgle's virtual keyboard also gets scaled up in response, which causes the keys not to all fit in the screen, meaning to use the keyboard you have to horizontally scroll back and forth.

The issue actually occurs both when changing the "font" size, as follows:
![Screenshot_20220204-202950_Impostazioni](https://user-images.githubusercontent.com/1684791/152592157-d8ec057b-b2ef-4905-8a2e-059cd3f0b179.png) ![Screenshot_20220204-202117_Gurgle](https://user-images.githubusercontent.com/1684791/152592177-3fcc8040-7b23-40b8-8ed0-f18a310ba767.png)

and when changing the "display" size, as follows:
![Screenshot_20220204-203000_Impostazioni](https://user-images.githubusercontent.com/1684791/152592203-7cb40053-b88e-49a8-a30f-c4d80e7448ce.png) ![Screenshot_20220204-202252_Gurgle](https://user-images.githubusercontent.com/1684791/152592218-0b7a02bd-984b-43bc-8f13-adca13d44327.png)

I'm running Gurgle 1.01 on Android 12.

**Comment by billthefarmer** [comment]
This has come up before, see #3. As it doesn't appear to be possible for an app to counteract the effect of the user adjusting the scaling, I added sideways scrolling to the keyboard.
