### ISSUE TITLE
[Feature Request] Color Blind Mode

### ISSUE THREAD

**Issue by jacobblackwood** [billthefarmer/gurgle#15]
I am color blind and I have trouble distinguishing the colors green and yellow.  Would it be possible to add the ability to change those colors to something else?

**Comment by billthefarmer** [comment]
OK, this is a selection of colours taken from [here](https://www.w3schools.com/cssref/css_colors.asp).

![Screenshot_20220223-153701 1](https://user-images.githubusercontent.com/3448386/155354170-2f6246f1-a21d-4cbe-9866-3b7eef7704d2.png)

**Comment by billthefarmer** [comment]
OK, this will be in the next version.

![Screenshot_20220225-134528 1](https://user-images.githubusercontent.com/3448386/155725967-559d430b-6fd4-4c3b-990f-6d9058329b08.png)

**Comment by jacobblackwood** [comment]
This is great.  Thank you so much for doing this.  Now I can play without pestering my family!
