### ISSUE TITLE
[feature request] real life problems

### ISSUE THREAD

**Issue by duckns** [billthefarmer/gurgle#18]
can we have a wowzer please

**Comment by duckns** [comment]
well ive got a bunch but my specific problem i am referring to i'll tell you about.
this morning im sitting on the couch, beside me sit my partner and our newborn, my partners mother is here too and our dog is curled up at our feet. we're playing gurgle togeather, lots of silly guesses are being made we're having a laugh, we're down to the last row, last try  my partner gives it a go, the anticipation is high...
the letters are all green, thats a correct answer but wheres all the whizz bangs? whoop whoops? some screen flashing lightbulbs maybe? how about a well done?
a little win in life still deserves a little pat on the shoulder no?
i think it would be wicked if you played a tune on your accordion when we won the game but maybe im getting a bit carried away
anyway cheers mate keep having fun with the programming

**Comment by AlreadyFree** [comment]
I agree, guessing correctly does seem to be a bit anticlimactic. It seems there should be some acknowledgement of winning beyond all the letters simply turning green. A little animated firework or balloon. Or a sound. Or congratulatory message. Or something...

**Comment by billthefarmer** [comment]
OK, the next version will have some music and a message. :shipit:

**Comment by AlreadyFree** [comment]
Awesome! Pavlov reinforcement!
