### ISSUE TITLE
Use native keyboard

### ISSUE THREAD

**Issue by fuzxi** [billthefarmer/gurgle#20]
The keys on the built-in keyboard are in an awkward place at the center of the screen. Being able to use the native keyboard of the user's choice would be much more comfortable.

**Comment by billthefarmer** [comment]
I'm not going to do that because it would be a major rebuild of the app, and it wouldn't be possible to highlight the keyboard keys.

**Comment by fuzxi** [comment]
Fair enough, thanks for considering it.

**Comment by billthefarmer** [comment]
But I will look at moving the keyboard nearer the bottom. I assume you have a long/tall phone, compared to older/smaller ones.

**Comment by pnrao** [comment]
![Screenshot_2022-03-10-09-18-40-638_org billthefarmer gurgle](https://user-images.githubusercontent.com/1281776/157584819-14d7fdb3-4906-4504-96cc-563a516fe310.png)

Please consider reducing gaps between keys, or some kinds of settings to reduce the keyboard width. The full keyboard isn't visible on some tall phones.
