### ISSUE TITLE
Versions >=1.02 crash on startup on Android 4.1

### ISSUE THREAD

**Issue by Anonymous1157** [billthefarmer/gurgle#21]
One of my devices is a Huawei Y301A1 and I had to downgrade to 1.01 for the game to run. Newer versions briefly show a default empty app view with a top bar and then crash.

In case this was deliberate, that's fine, I just wanted something cool to do with an EOL device. But then I don't have anything running 4.4 or 5.0 to find out the minimum version that still works so you could bump the requirement.

**Comment by billthefarmer** [comment]
The reason later versions of the app crash on earlier versions of android is because of the [zxing](https://github.com/zxing/zxing) library I am using to create and decode QR codes. I thought the android build system would pick that up, but it didn't.
