### ISSUE TITLE
[Feature Request] High contrast / e-ink compatible mode

### ISSUE THREAD

**Issue by Anonymous1157** [billthefarmer/gurgle#22]
A game like Gurgle is a really good fit for an e-ink Android tablet. The screen contents are clearly defined and barely change. Unfortunately, at least on my tablet, the gray and yellow letters are the same color, and it's impossible to tell them apart. The app itself runs fine, I just can't see what I'm doing.

![einktab](https://user-images.githubusercontent.com/8900271/156783549-71936b48-e98c-46ff-9092-10d1e1b1962b.png)

This request overlaps a little bit with #15 since it should be possible to make the game playable with those changes. On my tablet, that will probably be enough, but e-ink devices are not at all standard, and not every device will have features like adding a text outline that helps with readability for apps like this. A deliberate high contrast mode would be even better.

Here's a mock-up of one way it could work. (I used a screenshot from a different device with a tiny resolution so it wouldn't be a pain in the butt to make the mock-up.)

![mockeink](https://user-images.githubusercontent.com/8900271/156780434-4bafd8c0-b3ad-43f0-913b-5529721bd839.png)

**Comment by Anonymous1157** [comment]
I hadn't realized the color blind feature is already out! It turns out it does not help me. My tablet's text outline feature also forces the font colors to be black or white, so I had to turn that off to try it, and now the menus are solid white and the game is a muddy gray mess. The game simply doesn't have enough contrast to make it playable.

**Comment by billthefarmer** [comment]
The colour dialog won't help because the colours are intentionally fully saturated. There is a limit to what can be done in android with styles. I could make a high contrast black and white mode, but it's not possible to produce anything like your mockup without redesigning the app.

**Comment by billthefarmer** [comment]
OK, a black theme is in the next version
