### ISSUE TITLE
Fix text size when using small device font

### ISSUE THREAD

**Issue by StevenAlexander44** [billthefarmer/gurgle#23]
![Screenshot](https://user-images.githubusercontent.com/64290624/158034434-12c61e26-0d45-48b0-a433-09d60479a00b.png)

If you need screenshots from android (11) settings I'd be happy to post that

**Comment by billthefarmer** [comment]
If you make the text smaller, the text gets smaller, if you make it bigger, it gets bigger. What did you expect to happen? See #12, #3.
