### ISSUE TITLE
Feature request: Add German language dictionary support

### ISSUE THREAD

**Issue by lintux** [billthefarmer/gurgle#24]
Hi,

would be great to play gurgle in German. 

BR
lintux

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

**Comment by lintux** [comment]
Great thanks

**Comment by NichtJens** [comment]
(If this is better opened as a new issue, please let me know)

It seems either the German word list or its interpretation is a bit wrong. The first German word I got was "kurzt", which is not a word. Is it possible that "kürzt" (a conjugated form of the verb "kürzen") was meant? In that case, the normal crossword rules say it should be "kuerzt" (which is of course too long for the usage here). Could it be that the interpretation of umlauts is wrong?

**Comment by lintux** [comment]
@NichtJens - I guess that should better be a new request. 
I have not had a word with a german umlaut so far but was wondering already how this would be managed.
As I understand the word lists are coming from a different project. 
If these contain words with the umlaut they would either have to be ignored or transformed like this is usually done in German Crosswords. The gurgle keypad is not language specific and does not offer those.
For example, Mütze would be then Muetze (ä -> ae, ö -> oe, ü -> ue, ß -> ss) .
Seems to me quite some effort and for sure is worth a seperate issue - if the effort is acceptable at all.

**Comment by NichtJens** [comment]
I was indeed thinking this could be solved/fixed on the word list without touching the code at all. I was gauging the effort as fairly small if the full word list was around. I could even volunteer to do it, if that helps :)

Simply removing the ¨ from the vowel will not work for German text. The proper replacement is this:

```
ä -> ae
ö -> oe
ü -> ue
ß -> ss
```

Some French loan words are commonly used and thus could be fine to keep. Funnily, "voten" (in your example) is a conjugated loan word from English, which is considered [only colloquial](https://www.duden.de/rechtschreibung/voten).

**Comment by saskra** [comment]
As far as I know, crossword puzzles do not traditionally use inflected forms. Is it not possible to exclude them automatically if you want to, at least in Wiktionary they are marked as such?
