### ISSUE TITLE
Improve letter hint color rules

### ISSUE THREAD

**Issue by masonh** [billthefarmer/gurgle#25]
I understand "This app doesn't pretend to be a Wordle clone," and I haven't played that game, but my understanding of its highlighting rules based on the link in #14 match how I would prefer to play the game.
Basically, green letters take precedence, and yellows appear up to (`n` - `green`) times, where `n` is the count of that character in the correct word (e.g. 2 "o" in "foods").

**Comment by masonh** [comment]
![Image_69](https://user-images.githubusercontent.com/1444864/158275859-e8528a46-9b36-4b5b-98d7-e55c9913e062.jpg)

for example, the yellows in this game hid the greens in the second and third guesses.

**Comment by billthefarmer** [comment]
OK, I have released a new version which should fix that.

**Comment by masonh** [comment]
I played a few games on 1.07. Looks nice! No unexpected colours so far. I think this can be closed.
