### ISSUE TITLE
Feature request: pause Game / Save status

### ISSUE THREAD

**Issue by lintux** [billthefarmer/gurgle#27]
In cases where you are interrupted by something else, it might me nice to optionally save the current Game to continue later.
That could be by a general option to always save when you leave the game, or by a direct save button on the interface you have to tap on before leaving or switching apps.
btw. thanks for the German language add ;-)

**Comment by billthefarmer** [comment]
If you are interrupted by a phone call, message or whatever, and don't explicitly close the app, it will sit in the background until you go back to it. Unless android runs out of memory and closes it. Use the home button, not the back button.

The app saves the theme, language and highlight colours permanently, but not the current game.

**Comment by lintux** [comment]
ok, I tried to montor which way I use to close the app and the home button seems to minimize the problem. Only for a longer pause, I had the impression the screen was blank after starting the app again.

**Comment by billthefarmer** [comment]
Depends what you mean by 'the screen was blank'. If you mean that the last game was reset, the app was closed, probably because Android needed the memory. Also I think later versions may close apps that have been sitting unused for a long time.

**Comment by lintux** [comment]
Yes, Game was reset. It's Android 10 on a Nokia Phone. I remember some Information about Nokia also adding some aggressive memory and power consumption software. Let me check if the game can be excluded somewhere.
If the intention is that the game will be reset, when closed (either by user or by android) we can also close the topic.

**Comment by billthefarmer** [comment]
Android gives developers two options for saving state, one is for preserving the state of an app while it is running and may be paused in the background, and the other is for preserving options permanently, or until the app is uninstalled. There isn't an in between option for recovering state if an app is closed. It's possible to set up something like a database, which apps like email, messaging apps, calendar apps, contacts apps might use, but that is an overkill for a fairly simple game app.

**Comment by lintux** [comment]
> It's possible to set up something like a database, which apps like email, messaging apps, calendar apps, contacts apps might use, but that is an overkill for a fairly simple game app.
I agree - that would be too much ..
