### ISSUE TITLE
Big screen, tiny UI

### ISSUE THREAD

**Issue by onkoe** [billthefarmer/gurgle#28]
Could you please consider making the UI scale with device size? I have some beefy fingers and these buttons are tiny! Thanks for a nice offline game to play - with this change, it should be quite fun!

**Comment by onkoe** [comment]
Here's a screenie of the issue: https://imgur.com/a/kNPYjGK

**Comment by billthefarmer** [comment]
That is approximately the same as I get on my Pixel 3a, the only difference from a Moto G is that the keyboard is at the bottom, so one handed users can use their thumb. See #20

**Comment by onkoe** [comment]
I see. It may be worth eventually creating a settings screen with a couple different keyboard implementations, though that's up to your preference. It's hard to ask of that from a side project which is only a few months old. That said, I hope to eventually see a fix for my unique combination of sausage fingers and large screen. :)
