### ISSUE TITLE
Keyboard cut off

### ISSUE THREAD

**Issue by rudolfmu** [billthefarmer/gurgle#3]
On my phone with a 1520x720 display the keybard is cut off on the right, P and Backspace are missing.
On my 1280x800 tablet it is ok.

**Comment by billthefarmer** [comment]
I can't reproduce that. I tested on an emulator with 1520x720 resolution and the app works fine.

![Screenshot_1643051722](https://user-images.githubusercontent.com/3448386/150860857-86cb9c6f-230d-4170-8d8f-e398c543b424.png)

**Comment by billthefarmer** [comment]
If you make the text larger in the settings I can reproduce that on a 720 pixel width phone. I will make the keyboard scroll sideways because the app can't force the text smaller if the settings have made it larger.

**Comment by rudolfmu** [comment]
Thank you for the quick answer.
If I set my system text size smaller, I get the full keyboard.

**Comment by jmichael2497** [comment]
i was going to point out the increased font size cut off issue, but noticed the scrolling method by accident (thanks to scrollbars being auto-hidden for os "aesthetics").

alternatively, was going to ask why no landscape option? that seemed the natural solution when i noticed the keyboard cut-off, but seems to be portrait only.

**Comment by billthefarmer** [comment]
I have allowed the app to rotate, but then it needs to be scrolled up and down.
