### ISSUE TITLE
Impossible to play on certain aspect ratios

### ISSUE THREAD

**Issue by Millennium-Eagle** [billthefarmer/gurgle#31]
![Screenshot_20220403-003128_Gurgle](https://user-images.githubusercontent.com/17091484/161412235-b527261d-cb2c-4768-9c14-ed2b4141a248.png)

The keyboard does not transform properly to accomodate unexpected aspect ratios. This issue was also in 1.07 (first image), but oddly, this second instance (second image) did NOT happen on 1.07. It looked fine on this other screen until I updated:

![Screenshot_20220403-003144_Gurgle](https://user-images.githubusercontent.com/17091484/161412541-1cb89b84-cf99-4740-afa9-3693ff015052.png)

**Comment by billthefarmer** [comment]
You appear to have increased the display size. This will do exactly what it says. I have no idea what the second image is. Here are two screenshots of a phone similar to yours with the font size set to maximum. In landscape the display will scroll. In portrait the keyboard will scroll sideways to accommodate those who increase the display size.

![Screenshot_20220403-114627_Gurgle 1](https://user-images.githubusercontent.com/3448386/161425511-8c975090-f2ac-4ebd-879d-a97377fb35ba.png)

![Screenshot_20220403-114646_Gurgle 1](https://user-images.githubusercontent.com/3448386/161425538-0aefb7fd-2ab7-4282-8fac-05e4ffe905cf.png)

**Comment by Millennium-Eagle** [comment]
Font size? Display size? Where are these options? I didn't even know they existed.

The first screen is not the all that similar to yours. It is 25:9, which is much taller. Yours is 18.5:9. However, the ability to scroll the keyboard left and right does help; I wish it was in the instructions.

The second screen is closer to 3:4, but is too weird to be exact. It DID look fine until the update; I had not changed any settings. If there is a way to change font and display size within the app, please list it in the instructions and let me know how to do it.

**Comment by billthefarmer** [comment]
It is not the function of app developers to teach users how to use their devices. The display size and font size settings are in Settings->Display. I don't think it is possible to design this app to work on a device with a 3:4 aspect ration. I doubt of some of my other apps would work either. The scrolling is mentioned in several closed issues. Check the closed issues before raising another one.

**Comment by Millennium-Eagle** [comment]
It was not made clear to me that you were talking about device settings and not settings within the app. Regardless, I have not touched those settings between updates, and yet the second issue exists. 
I can only suggest automatically scaling the letter boxes until the bottom of the keyboard is visible, although I'm not sure that would be any easier than making the keyboard autoresize without the user changing system settings.

Instructions should still be given about the ability to scroll the keyboard somewhere within the app so users don't have to go to closed github issues to find out how to work it, or otherwise find out how to do it by accident.
