### ISSUE TITLE
Optional Enter button at bottom/right

### ISSUE THREAD

**Issue by BWPanda** [billthefarmer/gurgle#34]
It feels weird and unnatural having the Enter button on the left side of the keyboard. I understand from https://github.com/billthefarmer/gurgle/issues/6 that there have been many issues and opinions regarding the keyboard, so I propose **providing an option in the settings that determines where the Enter button is located**. Then everyone can set it to what works best for them.

Something like:
- Enter left, Backspace right
- Backspace left, Enter right
- Enter below keyboard

**Comment by billthefarmer** [comment]
That's an interesting one. Both Enter and Backspace belong on the right, but you can't do that with a purely alpha keyboard. Wordle solved it by putting enter on the left, which IMHO, is the least worse compromise.
