### ISSUE TITLE
error when 2 occurrences & first wrong place 

### ISSUE THREAD

**Issue by lakonis** [billthefarmer/gurgle#35]
![Screenshot_2022-04-18-20-57-27-765_org billthefarmer gurgle](https://user-images.githubusercontent.com/9479788/163860685-b0624576-c471-47d1-93b3-444a6dbba878.jpg)

As you can see on the second line, the last `e` was correct.

**Comment by billthefarmer** [comment]
I think I fixed that bug two releases ago, it's not in the latest version [1.09](https://github.com/billthefarmer/gurgle/releases).

![Screenshot_20220419-093222 1](https://user-images.githubusercontent.com/3448386/163960881-1e6aa9de-addc-47c3-9749-2833416e38ae.png)

**Comment by lakonis** [comment]
Great ! thanks
