### ISSUE TITLE
License for dictionary files

### ISSUE THREAD

**Issue by adolfintel** [billthefarmer/gurgle#36]
Hi Bill,

I'm developing a similar open source game for another platform, do you mind if I use your dictionary files? You'll be credited in the game obviously.

Thanks,

Federico

**Comment by billthefarmer** [comment]
Sorry about the delay. I got these dictionaries from [Lexica](https://lexica.github.io/lexica/) and [Lexique](http://www.lexique.org/shiny/openlexicon/), suggested by contributors. You are welcome to use mine, or get your own from these resources, but the credits belong to them.

**Comment by adolfintel** [comment]
Thanks Bill
