### ISSUE TITLE
Lost or wasted space on display of new phone.

### ISSUE THREAD

**Issue by original-dirigible** [billthefarmer/gurgle#37]
Just upgraded my phone.  Nothing special, just a Samsung S32 4g.  The keyboard and word grid look much smaller on the newer display and really need to be made bigger to fill it out.  
Display specs
6.4 inches
1080 x 2400 pixels
411 PPI
Would be happy to email a screenshot to you.

**Comment by billthefarmer** [comment]
It's difficult. I have a layout for larger devices which works fine on a tablet, but not, apparently, on some larger phones. Here are some screen shots of a Moto G, 4.5", Pixel 3a,, 5.6", Pixel 4XL emulator, 6.3", and Samsung tablet, 8". There is a plethora of different devices out there with different display sizes and densities. It's not possible for a lone developer to fit them all.

![Screenshot_20220520-144423 1](https://user-images.githubusercontent.com/3448386/169546571-dda8849f-7ff0-425b-bbd4-45507f6d9762.png)

![Screenshot_20220520-144343_Gurgle 1](https://user-images.githubusercontent.com/3448386/169547027-8ddeaf2f-5473-4354-80c6-6fdb0dc6130d.png)

![Screenshot_1653055423](https://user-images.githubusercontent.com/3448386/169547183-3638ba11-8c5a-42ea-a374-d48770a53f0e.png)

![Screenshot_20220520-144451_Gurgle 1](https://user-images.githubusercontent.com/3448386/169547524-15474e9e-dbf1-42c8-a35a-84bb6205e508.jpg)

**Comment by original-dirigible** [comment]
Hello Bill,

Mine looks like the 3rd one.

I was hoping it may be possible to put some options for custom Positioning
and Scaling of the word grid and keyboard in the Settings Menu.

If you don't have the resources to do that I completely understand.

Thanks for the reply,
