### ISSUE TITLE
Feature request: Get the meaning of all existing words

### ISSUE THREAD

**Issue by bovergaauw** [billthefarmer/gurgle#38]
Would it be possible to make it possible to get the meaning of all existing words rather than only the final word? This would be a great language learning feature that you apparently developed already.

**Comment by billthefarmer** [comment]
OK, that will be in the next version

**Comment by bovergaauw** [comment]
Thanks for having added this great feature, it will make Gurgle even more addictive to me 😊. To make my addiction even worse, would it be possible to check the meaning of existing words *prior* to having guessed the word? Not for impatient players, but to allow them to check those guesses that have scrolled out of screen.
