### ISSUE TITLE
Feature request: Get meaning of words prior to correct guess

### ISSUE THREAD

**Issue by bovergaauw** [billthefarmer/gurgle#39]
Would it be possible to get the meaning of guessed incorrect words prior to having guessed the correct word? Not for impatient players, but to allow them to get the meaning of those guesses that have scrolled out of screen.

**Comment by billthefarmer** [comment]
This words don't actually scroll, they just get moved up a slot, so the top one gets overwritten. If you want the meaning of a word, get it before it's lost.

**Comment by bovergaauw** [comment]
That's exactly my point, you can only get the meaning of an attempt when it's still on screen *and* you guessed the solution. It would be great to be able to look up any accepted attempt even before guessing the solution.

**Comment by billthefarmer** [comment]
Apologies, I thought I had released the version with that change but I hadn't.
