### ISSUE TITLE
Tickle out the keys not in the word

### ISSUE THREAD

**Issue by foldfree** [billthefarmer/gurgle#4]
![Screenshot_20220125-123701_Quickstep_1](https://user-images.githubusercontent.com/34523150/150911915-c9162124-14f7-4a51-a340-a18d5e47c6ea.png)
Just like wordle, could you darken out or else the keys not part of the word?

**Comment by billthefarmer** [comment]
OK, I missed that.

**Comment by original-dirigible** [comment]
Or perhaps turn spent letters red in keeping with traffic light colours.
