### ISSUE TITLE
Only allow giving meaning of accepted words

### ISSUE THREAD

**Issue by bovergaauw** [billthefarmer/gurgle#41]
First of all, thanks for allowing getting the meaning of words prior to guessing the solution. However, Gurgle now allows for getting the "meaning" of any 5-letter sequence, even prior to validation of such sequence as a valid guess. Would it be possible to change that for a cleaner "user experience" (even though I hate that expression...)?

**Comment by billthefarmer** [comment]
OK, that will be in the next version.
