### ISSUE TITLE
Toasts are unreadable

### ISSUE THREAD

**Issue by ayesc9000** [billthefarmer/gurgle#43]
No matter what theme is selected, the text color of the toast messages is the same as the background, making them unreadable. 

Using a Pixel 5 running Android 13 Beta 4 with system dark theme enabled. 

![Screenshot_20220720-164413](https://user-images.githubusercontent.com/29239155/180078274-2fe440eb-97ca-43aa-898f-173e63872a19.png)

**Comment by billthefarmer** [comment]
I haven't tested android 13, it looks to me like an android own goal because toasts up to android 12 ignore themes, always have the same style regardless. I will investigate.
