### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by airon90** [billthefarmer/gurgle#44]
How can I translate the app?

**Comment by billthefarmer** [comment]
It depends what you mean. If you want to use it in a language, provide a list of common words in that language. If you mean to translate the messages, etc the app uses, translate the strings in [strings.xml](https://github.com/billthefarmer/gurgle/blob/main/src/main/res/values/strings.xml) and post it here or as a pull request. See https://developer.android.com/guide/topics/resources/localization.

**Comment by airon90** [comment]
[Help](https://github.com/billthefarmer/gurgle/blob/main/src/main/res/raw/help.html) is not translatable, AFAIK

**Comment by billthefarmer** [comment]
You can put a translation in `raw-it/help.html`. Contributors have done this with some of my other apps.

**Comment by airon90** [comment]
Too long, I will do it another day. You can merge my edits in #45

**Comment by airon90** [comment]
![p1](https://user-images.githubusercontent.com/139841/181262924-8f9c25ad-94bb-49f6-852a-8cf1e68f7a89.jpg)

![p2](https://user-images.githubusercontent.com/139841/181262915-ec01d569-0013-48bf-b80b-887bb8556b66.jpg)


Please, can you add these screenshots under `/metadata/android/it/images/phoneScreenshots/`? Thank you very much!

**Comment by billthefarmer** [comment]
OK

**Comment by billthefarmer** [comment]
I have pushed the changelog for the next version with your translations and other changes. Would you like to check the [Italian translation](https://github.com/billthefarmer/gurgle/blob/main/fastlane/metadata/android/it/changelogs/112.txt) please.

**Comment by airon90** [comment]
Done. Thabk you very much! Please ping me for other keys/changelogs to be translated 😊
