### ISSUE TITLE
Sharing an incomplete grid displays the solution

### ISSUE THREAD

**Issue by arodier** [billthefarmer/gurgle#5]
I wanted to share a game to ask for help, and when it was about to be shared, I saw the solution displayed.

Is it a feature ;-) ?

**Comment by RealDudePerson** [comment]
Can confirm, same happened to me.

**Comment by billthefarmer** [comment]
Well it was a feature I left in for testing. It didn't show up in any of the apps I tried.

**Comment by arodier** [comment]
Thanks!
