### ISSUE TITLE
Avast Antivirus flags Gurgle as 'suspicious'

### ISSUE THREAD

**Issue by Dao0fGeek** [billthefarmer/gurgle#50]
Avast needs to be informed re falsely flagging this app as 'a suspicious app that may harm your device'.

**Comment by billthefarmer** [comment]
Could be right, it uses garish colours and loud noises and might flatten the battery if you play all day :shipit:

**Comment by Dao0fGeek** [comment]
Just my guess, but Avast may be flagging new updates and installs from F-droid cuz it also flagged Sushi and OpenCalc which I had installed previously via F-droid - so they may all have been flagged after they updated. I don't have any other explanation. Just trying to be a "good neighbor" cuz if I'm getting them flagged then other Avast users are too. I do see that virustotal's version of the avast engine doesn't flag it or the others so it's probably unique to the android version of Avast's engine.

**Comment by jacobrogers256** [comment]
Uninstall your anti-virus. If you download APKs from teh interwebz, why should you care?
