### ISSUE TITLE
On fdroid

### ISSUE THREAD

**Issue by derpyderpaderp** [billthefarmer/gurgle#51]
Can we get a description of what this app is on fdroid? We have no screenshots or description.

**Comment by billthefarmer** [comment]
![Screenshot_20220804-173115 1](https://user-images.githubusercontent.com/3448386/182903474-66faf0cc-2c81-4140-ac79-9b397b913a05.png)

![Screenshot_20220804-173133 1](https://user-images.githubusercontent.com/3448386/182903612-471d1bc5-bc20-49f7-960b-6ff51f943b2a.png)
