### ISSUE TITLE
Info messages appear white-on-white on Android 13

### ISSUE THREAD

**Issue by gropius365** [billthefarmer/gurgle#55]
Version: 1.13
Repo: F-Droid

Since upgrading to Android 13 the app's info messages show as white-on-white text.  

I've tried fiddling with changing the theme and other in-app color settings to no effect.

![gurgle_white-on-white](https://user-images.githubusercontent.com/4543253/188571419-99c38f1e-5d82-491d-959e-3bbdb5e6d5bc.png)

PS Love the game; thanks for creating and maintaining it!

**Comment by billthefarmer** [comment]
This appears to be a bug in android 13 which doesn't appear fixable by developers like me. See #43 and https://issuetracker.google.com/issues/245108402.

**Comment by gropius365** [comment]
Ah OK this is defo a dupe of #43 .  Will close.

The issue posted to the google issue tracker doesn't seem to be getting much love -- hope this gets addressed in Android 13  soon!

In any case the game is still playable for me...I've logged enough gurgle in-game hours to know the toasts by heart!

**Comment by gropius365** [comment]
Dupe of #43 .

**Comment by gropius365** [comment]
close

**Comment by gropius365** [comment]
trying to close as not planned (dupe)

**Comment by gropius365** [comment]
oh ffs github

**Comment by billthefarmer** [comment]
I have discovered a fix for this. It will be in the next version.

**Comment by billthefarmer** [comment]
I have found the comment thread on https://issuetracker.google.com/issues/245108402 somewhat amusing. The initial response infers that it's my fault for not using all the latest boondoggles from them, but then one of their own [confirmed it](https://issuetracker.google.com/issues/245108402#comment7) on their own system apps.
