### ISSUE TITLE
Retain accents in dictionaries

### ISSUE THREAD

**Issue by sotpapathe** [billthefarmer/gurgle#56]
This will help get the correct dictionary entries for languages that use accents, e.g. French. For example in the case of `ELIRE`, Wiktionary should be searched for `élire` instead of `elire`. The virtual keyboard and word display would remain as they are now, without accents.

Of course this would require updating the dictionary to contain the accents and remove the accents when testing whether a word is valid.

This is probably a lot of programming effort for little gain but it would be nice to have so I'm putting it here.

**Comment by billthefarmer** [comment]
I'm not going there, unless someone else wants to have a go. I spent some time carefully removing accents from the dictionaries and checking for duplicates so the app won't come up with unsolvable games. There is no algorithmic method, AFAIK, to get from accented letters to unaccented, so there would have to be a lookup table. There are rather a lot of accents, as I found when removing them.

**Comment by billthefarmer** [comment]
OK, a long press on a letter in a completed guess will show a pop-up menu with possible unaccented and accented characters for that letter. This makes it possible to add and remove accents.

![Screenshot_20220917-143008 1](https://user-images.githubusercontent.com/3448386/190859923-ed1bfc38-88a1-4f44-8c33-a7a7a9609c78.png)

**Comment by sotpapathe** [comment]
That's a nice workaround, thanks!
