### ISSUE TITLE
Locking Letters

### ISSUE THREAD

**Issue by fluidicice** [billthefarmer/gurgle#57]
Issue: When trialing various combinations of letters around letters you **know** are correct - it becomes tedious having to delete all 5 including the correct letters to attempt different combinations.

Proposal: Setting 'locked' letters which stay on the board. Typing new letters fills the blanks while ignoring the locked ones. Locking could be done through a letter drag-and-drop to the position you want (reversible by dragging them back off), or by a toggle switch above the keyboard when you get to the desired position of a letter you want fixed. Additionally, having blanks between known letters will make it easier to visualize possible combinations: " F L _ I _ "  rather than having to fill each slot with a letter.

P.S. I picked up the game yesterday and couldn't put it down since. <3

**Comment by billthefarmer** [comment]
This is possible. I would use a long press on the letter, which would turn grey. Another long press will unlock it and turn it white again. Locked letters will be skipped when typing in and deleting. This will not affect the scoring. I would use grey asI don't want to introduce another colour because of the dialog for changing the highlight colours. If the word has already been scored the long press will be ignored.

**Comment by fluidicice** [comment]
Hi Bill,
Thanks for your swift implementation, it almost works perfectly. I found two bugs and have two recommendations. (I'm not sure if you prefer a new bug issue per request or continued in this thread)

Bug 1: Type any number of letters on a new game and lock any number of them and restart the game before submitting the word. The previously locked letters will remain blank and un-fillable on the new game. Closing and reopening the game solves this issue.

Bug 2: Type any 5 of the same letter into a new game, lock all 5 letters, backspace 5 times and type 5 of a different letter. Letters in position #2 and #4 can be edited while locked.

Recommendation 1: Rather than the letters going dark when locked, the border around that letter could turn white to signify it's locked rather than the letter doing dark. (which normally means it's a wrong letter)

Recommendation 2: Based on Bug 2, it would be useful to see where the 'cursor' is currently. Perhaps the bottom edge of the box under the 'cursor's' position could slowly flash like when editing text. This would help visualize the letter you are currently at.

**Comment by billthefarmer** [comment]
OK, there were two issues with locking, which I have fixed. The cursor is at the first empty slot when adding letters and the last unlocked populated slot when deleting. I have added an option to change the shade of grey as requested for [Gridle](https://github.com/billthefarmer/gridle/issues/9).
