### ISSUE TITLE
Light Theme 

### ISSUE THREAD

**Issue by scottiefalkon** [billthefarmer/gurgle#58]
Could we get a theme with a white background and black text and elements. Great app.

**Comment by billthefarmer** [comment]
Needs a major redesign as it's built around the dark theme, so I'm not going there.

**Comment by scottiefalkon** [comment]
Understood.

**Comment by billthefarmer** [comment]
After a bit of thought, I got this working...

![Screenshot_20221004-105135 1](https://user-images.githubusercontent.com/3448386/193816843-1bb86efc-7e5e-49ad-8647-a277c9d51df7.png)

**Comment by scottiefalkon** [comment]
That looks great!
