### ISSUE TITLE
Recommend add Themes and big ENTER Button

### ISSUE THREAD

**Issue by PoorLazyCoder** [billthefarmer/gurgle#6]
![theme (1)](https://user-images.githubusercontent.com/98500513/151273851-cbbf152c-9b09-4c29-9a3f-5713ecdaa596.png)
![theme (2)](https://user-images.githubusercontent.com/98500513/151273854-2cdbb178-0b93-49ca-8430-422790179a0e.png)
![theme (3)](https://user-images.githubusercontent.com/98500513/151273855-6ddc43b1-e33d-45f0-bcd1-99dd666c27ba.png)
![theme (4)](https://user-images.githubusercontent.com/98500513/151273858-4bf7c1f5-3cb0-4229-9130-c7a055421785.png)
![theme (5)](https://user-images.githubusercontent.com/98500513/151273859-563efa27-cb27-48dc-b2c1-6d1bd54a315c.png)
![theme (6)](https://user-images.githubusercontent.com/98500513/151273860-186d69fa-e159-466c-9621-b9bd05b907b8.png)

**Comment by billthefarmer** [comment]
OK, that will be in the next version. I like your themes, how did you create them?

**Comment by BWPanda** [comment]
@billthefarmer I'm not seeing the large Enter button (v1.08)... Was that not included?

**Comment by billthefarmer** [comment]
I liked the themes, but not the button. I have enough problems with the keyboard being too big/too small, etc #31, #28, #23, #20, #12, #3.
