### ISSUE TITLE
Cannot see lower row of letters

### ISSUE THREAD

**Issue by Asinine17** [billthefarmer/gurgle#60]
![Screenshot_20221024-202433](https://user-images.githubusercontent.com/38194416/197654476-a1723043-4733-4546-9c7e-cfe6f2465144.png)
Lower row of letters are not visible. I'm using a Razer Phone 2, rooted with Android 9. Please let me know if you'd like more info.

**Comment by billthefarmer** [comment]
I can't reproduce this. I have tested on a Pixel XL android 9 emulator, which has the same screen resolution as a Razer Phone 2, 2560x1440. Have you increased the display size in the device settings? (Settings>Display>Display size)

![Screenshot_1666951372](https://user-images.githubusercontent.com/3448386/198563934-37987095-c69d-409f-8a75-faa3bdcdb66b.png)

**Comment by Nighted** [comment]
This happens on Android 11 / Pixel 3a. You have to swipe the alphabet back and forth. It is very annoying.

**Comment by Asinine17** [comment]
> This happens on Android 11 / Pixel 3a. You have to swipe the alphabet back and forth. It is very annoying.

Glad to see it's not just me. My phone's display is 1440p/1440x2560, and I may be needing glasses soon... so I'm not about to zoom out more.

**Comment by billthefarmer** [comment]
As it happens, I have a Pixel 3a. If you increase the font size to largest and the display size to large you get a display as below. Increasing the display size to largest makes the keyboard scroll.

![Screenshot_20230206-091732_Gurgle 1](https://user-images.githubusercontent.com/3448386/216934307-c9129d91-b5b0-40fa-80ef-93fb966f1950.png)

**Comment by Nighted** [comment]
I like my fonts the way they are. If I increase the size it messes up everything else that I spent hours tweaking. Gurgle didn't have this issue before so I suppose I can live with it since it is the only app that isn't playing nice with my system settings.

Thanks for the reply and the great software. 👍
