### ISSUE TITLE
Dark mode Toast message colors

### ISSUE THREAD

**Issue by sanctimoniousape** [billthefarmer/gurgle#61]
Toast messages in dark mode are black on dark grey - kinda difficult to read.

**Comment by billthefarmer** [comment]
Which version of android are you using and on what device? There is a bug in android 13 that causes white on white toasts, #55, but I have fixed that. I have just tested on the latest android 13 emulator and the fix still works.

**Comment by sanctimoniousape** [comment]
OnePlus 7 Pro on Android 11. 
![Screenshot_20230122-093824](https://user-images.githubusercontent.com/80165446/213921780-c463558a-4649-4daf-bd78-bf1fc935e6cc.jpg)

**Comment by billthefarmer** [comment]
OK, I've got it. That will be fixed in the next version.

![Screenshot_1674574004](https://user-images.githubusercontent.com/3448386/214336081-103015ca-37ac-4916-a173-1690617e4749.png)
