### ISSUE TITLE
Keep all lines visible

### ISSUE THREAD

**Issue by peter099** [billthefarmer/gurgle#63]
When making more than 6 suggestions the first lines are pushed upward and become hidden. That make it hard to remember where is the position of the yellow letters in these hidden lines. Maybe option to scroll down the list of lines will be good solution to solve this issue.

**Comment by billthefarmer** [comment]
The app uses a fixed size grid to display the guesses and scrolls up when necessary. Old guesses are lost once they scroll off the top. I have already implemented several requested enhancements, to implement this would require an extensible grid or some sort of record of previous guesses. You only get six guesses in the original Wordle. I am not going to attempt to implement this. However, as with all open source apps, you are welcome to fork it and implement your own version or submit a pull request.

**Comment by peter099** [comment]
I am not a coder so i don't know how hard is to implement feature like this. I just use [this](https://play.google.com/store/apps/details?id=io.digitalsnacks.wordchallenge) app before and it has this feature.
