### ISSUE TITLE
REQ: "Capitulate" option

### ISSUE THREAD

**Issue by sanctimoniousape** [billthefarmer/gurgle#64]
When I just can't figure out the word, but still want to know what it is I'm forced to go through your solver app to find out.  It's a bit too tedious at times.  Could you please add a menu option (or whatever method you prefer to make it harder to accidentally trigger) to just show the word?  Display it in red or inverse to indicate the player didn't figure it out if you like.

Thanks again.

**Comment by billthefarmer** [comment]
![Screenshot_20230410-095748 1](https://user-images.githubusercontent.com/3448386/230881240-0063fd89-bd91-484c-ad9b-c8b4be4d123c.png)  ![Screenshot_20230410-095806 1](https://user-images.githubusercontent.com/3448386/230881380-d1824092-c83c-4290-9e46-e6f412b8ecb1.png)

**Comment by sanctimoniousape** [comment]
Oh, you tease!  ;-D

Thank you once again for such an incredibly expedient implementation!  VERY much appreciated!
