### ISSUE TITLE
Add a timed option

### ISSUE THREAD

**Issue by grrrrr** [billthefarmer/gurgle#7]
It would be great to have an option in gurgle for timed play to add an additional challenge element.

This is similar  to how the revival of the 80's TV show in the UK called [Lingo](https://en.wikipedia.org/wiki/Lingo_(British_game_show)) currently works.  You have [10 seconds](https://en.wikipedia.org/wiki/Lingo_(British_game_show)#General_Rules) for each line guess to find the correct word

( If you could work out how to give £200 for correct answers that'd be a bonus :smile:  )

**Comment by billthefarmer** [comment]
I'm not going there. However it's free software, so feel free to create your own version complete with cash prizes, preferably in cyptocurrency :trollface: :moneybag: :shipit:
