### ISSUE TITLE
Allow automatic updates

### ISSUE THREAD

**Issue by grrrrr** [billthefarmer/gurgle#70]
With 3rd party stores such as Droid-ify, Neo-Store and now F-droid, they can perform auto-updates of apps if the device is running Android 12 or newer.   This means that the end user does not have to confirm an "install" prompt each time Gurgle updates.

I'd like to suggest that Gurgle implements this feature.  It would require supporting `TargetSDK 31` instead of the current 28.

Further details here: 

https://developer.android.com/about/versions/12/features#automatic-app-updates

**Comment by billthefarmer** [comment]
OK, that will be in the next version
