### ISSUE TITLE
[feature request] difficulty setting

### ISSUE THREAD

**Issue by tubbadu** [billthefarmer/gurgle#72]
Sometimes words are so unusual or niche. It would be nice to have the possibility to choose a lower difficulty level, where only more common words are used

**Comment by billthefarmer** [comment]
That is dependent on the availability of dictionaries. You can always cheat by using my [Wordlesolver](https://github.com/billthefarmer/wordlesolver) app. The problem may be exacerbated by the use of British(Welsh) English words.

**Comment by vi** [comment]
Alternative idea for difficulty levels: choosing a set of words instead of one word and refining the set each time user provides a solution in user's favour (easy mode) or against user (hard mode).

**Comment by billthefarmer** [comment]
That's a completely different algorithm and is deterministic, in that it is predictable. This app is random, it's only possible to make it predictable by sharing codes.
