### ISSUE TITLE
Feature request: absurdle mode

### ISSUE THREAD

**Issue by vi** [billthefarmer/gurgle#74]
Implement [Absurdle](https://qntm.org/files/absurdle/absurdle.html) mode with similar user input, but different underlying algorithm.

Ideally it should have two modes: deterministic (default Absurdle) and targeted (you need to arrive at a specific, visible word).

Some variation of the Absurdle algorithm may be used for [easy or hard modes for regular game](https://github.com/billthefarmer/gurgle/issues/72).

**Comment by billthefarmer** [comment]
I think that's another app, see https://github.com/billthefarmer/gurgle/issues/72#issuecomment-1798369148.
