### ISSUE TITLE
Feature Request: Disable Repeat Letters

### ISSUE THREAD

**Issue by ghost** [billthefarmer/gurgle#75]
I'd love to be able to disable the usage of words with the same letter twice. I never want to get `FOGGY` or `TALLY` or `OBOES` or anything similar.

Was always the reason I never played real Wordle. Feels "cheap" to me in some weird way. Maybe it's just me.

**Comment by billthefarmer** [comment]
If you remove words with duplicated letters it doesn't leave much of a game...
```shell
$ wc ../src/main/assets/Words.txt
 2314  2315 16203 ../src/main/assets/Words.txt

Bill@Cecelia MSYS /d/android/Gurgle/data
$ cat dup.py
f = open('../src/main/assets/Words.txt')
for line in f:
    dup = False
    for c in line:
        if line.find(c) != line.rfind(c):
            dup = True
    if dup:
        print(line, end='')
f.close()

Bill@Cecelia MSYS /d/android/Gurgle/data
$ python dup.py | head
aback
abase
abate
abbey
abbot
abyss
adage
adapt
affix
afoot

Bill@Cecelia MSYS /d/android/Gurgle/data
$ python dup.py | wc
    749     749    4494
```

**Comment by billthefarmer** [comment]
The English.txt file is possible allowed guesses, the Words.txt file is the list of randomly selected words used for the game. If someone comes up with a good idea, such as sharing games, or a dictionary for another language it gets added. Minority niggles like #72 and this I don't think add anything to the game.
