### ISSUE TITLE
Feature request: offline dictionary lookup

### ISSUE THREAD

**Issue by dfandrich** [billthefarmer/gurgle#76]
It would be nice to have an option to look up words in a locally-installed dictionary app instead of opening a URL, for a seamless offline experience. For reference, here's how [another word game does it](https://github.com/lexica/lexica/blob/master/app/src/main/java/com/serwylo/lexica/activities/score/WordDefiner.java).

**Comment by billthefarmer** [comment]
The code you linked to offers the option of Aard 2 or QuickDic. I would propose to offer the existing Wiktionary plus those, defaulting to Wiktionary if the apps aren't installed. I haven't investigated yet.

**Comment by dfandrich** [comment]
Super, thanks!

**Comment by elonmasai7** [comment]
thanks
