### ISSUE TITLE
Feature request: pre-fill a default first word

### ISSUE THREAD

**Issue by dfandrich** [billthefarmer/gurgle#77]
It would save some typing if Gurgle would pre-fill a user-selected default word at the start of every new game. It would still be up to the user to hit Enter to play the word, so it could still be changed to something else if that game needs a different lucky word.

**Comment by billthefarmer** [comment]
OK, that's a reasonable idea. The first word entered will become the default word if the default word option is set, clearing the option will clear the default word.
