### ISSUE TITLE
Keyboard too wide

### ISSUE THREAD

**Issue by albatros69** [billthefarmer/gurgle#78]
Since recently, the keyboard is larger than the screen (see screenshot). You still can access all the keys by sliding horizontally, but it's not very practical.
![Screenshot_20240124-141821](https://github.com/billthefarmer/gurgle/assets/5740149/fa4cf4b0-c986-44a3-833f-8cf2f0df4c51)

Plateform: Pixel 7a (Android 14, last patch update)

**Comment by billthefarmer** [comment]
I have tested this on a Pixel 7 emulator running android 14...

![Screenshot_1706179683](https://github.com/billthefarmer/gurgle/assets/3448386/966567f0-22e8-46e2-8ccc-898859dadd55)

If the display size in the device settings is set to the absolute maximum it is possible to get the keyboard to overflow. However at all other settings of display and font size the app fits on the display. The app attempts to compensate for this but it is not possible for all devices and the extremes of the possible settings.

**Comment by elonmasai7** [comment]
great work

**Comment by sanctimoniousape** [comment]
I'm also having this problem and I don't think my settings are "extreme" - I have the display size set to the smallest possible (I don't need or like large icons), and the font size set exactly in the middle of the possible range.

Android 14 on a Pixel 7 Pro. 

![Screenshot_20240422-144206](https://github.com/billthefarmer/gurgle/assets/80165446/0085949a-d2b5-44b3-96d3-90f0d261b338)

Gets: 

![Screenshot_20240422-143905](https://github.com/billthefarmer/gurgle/assets/80165446/84786d00-7202-4f86-9f4a-37631473af81)
