### ISSUE TITLE
Feature request: highlight and tap to select letter entry

### ISSUE THREAD

**Issue by kboran** [billthefarmer/gurgle#79]
It might be nice if tapping on a box would select it, so the next letter entry occurs at that box. The box could be highlighted to show that it is the active one.

The current behavior of looking up the definition of a word is useful, but the "Finish the word first" toast for an incomplete word doesn't do much useful. This could replace that, and I've seen another similar app that does it this way (but is an ad-riddled mess). Thank you for a useful and clean app!

**Comment by billthefarmer** [comment]
OK, that will be in the next version. Note that just typing will overwrite unless letters are locked.

**Comment by kboran** [comment]
Tested and confirmed that it seems to work fine in 1.28. Thank you for the quick work!
